### ISSUE TITLE
How to import functions, how to interact with the code outside the string,How to use the REPL mode in the Golang language

### ISSUE THREAD

**Issue by ghost** [sbinet/igo#7]
How to import functions, how to interact with the code outside the string

**Comment by ghost** [comment]
how to eval string like python eval on golang,is there a code example?

**Comment by ghost** [comment]
how to eval string like python eval which can interact code outside of string on golang,is there a code example?

**Comment by ghost** [comment]
How to use the REPL mode in the Golang language

**Comment by sbinet** [comment]
Igo was an early attempt at providing a Go interpreter.
Never finished.

I'd recommend to use cosmos72/gomacro instead.
Or yaegi.
